# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Submission Form
    url: https://forms.gle/REgwJQBP8ZXQEaJk7
    weight: 20
  - name: Past Iterations
    identifier: past
    url : #
    weight: 30
  - name: MLRC 2023
    url: /proceedings/mlrc2023/
    weight: 5
    parent: past
  - name: MLRC 2022
    url: https://paperswithcode.com/rc2022
    weight: 10
    parent: past
  - name: MLRC 2021
    url: https://paperswithcode.com/rc2021
    weight: 20
    parent: past
  - name: MLRC 2020
    url: https://paperswithcode.com/rc2020
    weight: 30
    parent: past
  - name: NeurIPS 2019
    url: https://reproml.org/neurips2019/
    weight: 40
    parent: past
  - name: ICLR 2019
    url: https://www.cs.mcgill.ca/~jpineau/ICLR2019-ReproducibilityChallenge.html
    weight: 50
    parent: past
  - name: ICLR 2018
    url: https://www.cs.mcgill.ca/~jpineau/ICLR2018-ReproducibilityChallenge.html
    weight: 60
    parent: past
  # - name: Task
  #   url: task/
  #   weight: 30
  # - name: Awards
  #   url: awards/
  #   weight: 40
  # - name: Resources
  #   url: challange_resources/
  #   weight: 50
  # - name: FAQ
  #   url: faq/
  #   weight: 60
